image: node:latest

stages:
  - build
  - deploy

build:
  stage: build

  script:
  - yarn
  - yarn build

  artifacts:
    paths:
    - dist/
  only:
  - main

deploy:
  stage: deploy
  script:
  - npm -g install cloudron-surfer
  - surfer put --token $SURFER_KEY --server sta.my.demo.cloudron.io dist/* /

  only:
  - main
